name: Deploy to OVH

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/deploy_key
          ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to OVH Server
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -e
            
            # Navigation vers le répertoire de l'application
            cd /home/${{ secrets.SSH_USER }}/lolirinepool || exit 1
            
            # Pull des dernières modifications
            git pull origin main
            
            # Installation des dépendances
            npm install --production
            
            # Build de l'application (si nécessaire)
            npm run build
            
            # Redémarrage de l'application (PM2, systemd, ou Docker)
            pm2 restart lolirinepool || pm2 start npm --name "lolirinepool" -- start
            
            echo "✅ Déploiement réussi!"
          EOF

      - name: Verify Deployment
        run: |
          echo "Déploiement terminé avec succès!"
          
      - name: Cleanup
        if: always()
        run: |
          rm -f ~/.ssh/deploy_key
