name: Deploy to OVH VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        env:
          VITE_DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npm run build

      - name: Debug SSH Key
        run: |
          echo "Vérification de la clé SSH..."
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | head -n 1
          echo "Longueur de la clé: $(echo '${{ secrets.SSH_PRIVATE_KEY }}' | wc -c)"
          
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'placeholder'
          if_key_exists: replace
          
      - name: Add Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 5.196.236.227 >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          
      - name: Test SSH Connection
        run: |
          ssh -vvv -o StrictHostKeyChecking=no ubuntu@5.196.236.227 "echo 'Connexion SSH réussie!'"

      - name: Deploy to OVH VPS
        run: |
          ssh ubuntu@5.196.236.227 << 'ENDSSH'
            set -e
            
            # Création du répertoire si nécessaire
            sudo mkdir -p /var/www/lolirinepool
            sudo chown -R ubuntu:ubuntu /var/www/lolirinepool
          ENDSSH
          
          # Transfer des fichiers buildés
          rsync -avz --delete dist/ ubuntu@5.196.236.227:/var/www/lolirinepool/
          
          ssh ubuntu@5.196.236.227 << 'ENDSSH'
            # Configuration des permissions
            sudo chown -R www-data:www-data /var/www/lolirinepool
            sudo chmod -R 755 /var/www/lolirinepool
            
            # Redémarrage de Nginx
            sudo systemctl reload nginx
            
            echo "✅ Déploiement réussi!"
          ENDSSH

      - name: Verify Deployment
        run: echo "🚀 Application déployée sur http://5.196.236.227"
