name: Deploy to OVH VPS
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: SSH deploy
        uses: appleboy/ssh-action@v1.0.3
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          APP_PORT: ${{ secrets.APP_PORT }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script_stop: true
          envs: DATABASE_URL,APP_PORT
          script: |
            set -euo pipefail
            APP_PORT="${APP_PORT:-3000}"

            if ! command -v docker >/dev/null; then
              curl -fsSL https://get.docker.com | sh
              sudo systemctl enable --now docker
            fi
            docker compose version || { sudo apt-get update && sudo apt-get install -y docker-compose-plugin; }

            mkdir -p ~/apps && cd ~/apps
            if [ ! -d "Pool-store-Lolirine/.git" ]; then
              git clone --depth=1 git@github.com:lolirine/Pool-store-Lolirine.git Pool-store-Lolirine
            fi
            cd Pool-store-Lolirine
            git fetch --depth=1 origin main
            git checkout -f main
            git reset --hard origin/main

            cd lolirinepool
            printf 'DATABASE_URL=%s\nPORT=%s\n' "$DATABASE_URL" "$APP_PORT" > .env

            docker compose down || true
            docker compose build --pull --no-cache --build-arg GIT_SHA=${GITHUB_SHA:-manual}
            docker compose up -d --force-recreate --remove-orphans

            docker ps --format 'table {{.Names}}\t{{.Status}}\t{{.Ports}}'
