name: Deploy to OVH VPS
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: SSH deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT || 22 }}
          script_stop: true
          script: |
            set -euo pipefail
            if ! command -v docker >/dev/null; then
              curl -fsSL https://get.docker.com | sh
              sudo systemctl enable --now docker
            fi
            mkdir -p ~/apps && cd ~/apps
            if [ ! -d "Pool-store-Lolirine/.git" ]; then
              git clone --depth=1 ${{ secrets.REPO_SSH_URL }} Pool-store-Lolirine
            fi
            cd Pool-store-Lolirine
            git fetch --depth=1 origin main
            git checkout main
            git reset --hard origin/main
            cd lolirinepool
            cat > .env <<EOF
DATABASE_URL=${{ secrets.DATABASE_URL }}
PORT=${{ secrets.APP_PORT || 3000 }}
EOF
            docker compose version || sudo apt-get install -y docker-compose-plugin
            docker compose down || true
            docker compose build --pull --no-cache --build-arg GIT_SHA=${{ github.sha }}
            docker compose up -d --force-recreate --remove-orphans
            sudo tee /etc/nginx/sites-available/poolstore >/dev/null <<NGINX
server {
  listen 80; listen [::]:80;
  server_name ${HOSTNAME};
  location / {
    proxy_pass http://127.0.0.1:${{ secrets.APP_PORT || 3000 }};
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
NGINX
            sudo ln -sf /etc/nginx/sites-available/poolstore /etc/nginx/sites-enabled/poolstore
            sudo nginx -t && sudo systemctl reload nginx
