name: Deploy to OVH

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'placeholder'
          
      - name: Add Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to OVH Server
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'ENDSSH'
            set -e
            
            # Navigation vers le répertoire de l'application
            cd ~/lolirinepool || exit 1
            
            # Pull des dernières modifications
            git pull origin main
            
            # Installation des dépendances
            npm install --production
            
            # Build de l'application (si nécessaire)
            npm run build
            
            # Redémarrage de l'application (PM2, systemd, ou Docker)
            pm2 restart lolirinepool || pm2 start npm --name "lolirinepool" -- start
            
            echo "✅ Déploiement réussi!"
          ENDSSH

      - name: Verify Deployment
        run: echo "Déploiement terminé avec succès!"
