name: OVH DB Migrations

on:
  push:
    branches: [ main ]
    paths:
      - 'db/migrations/**'
      - '.github/workflows/migrate.yml'
  workflow_dispatch: {}

concurrency:
  group: migrate-${{ github.ref }}
  cancel-in-progress: true

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install psql
        run: sudo apt-get update && sudo apt-get install -y postgresql-client

      - name: Apply SQL
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          set -euo pipefail
          for f in db/migrations/*.sql; do
            echo "Applying $f"
            psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f "$f"
          done
          
